package de.tilokowalski.db;

import lombok.Getter;

import java.util.Objects;

/**
 * A record is a node in the surreal graph database.
 * It is identified by a table name and a record id.
 */
public abstract class Record{

    /**
     * The record id is optional.
     * If it is not set, the record id will be generated by surreal
     */
    @Getter
    private transient String recordId;

    @Getter
    private transient String tableName;

    /**
     * Creates a new record.
     *
     * @param recordId The record id.
     */
    protected Record(String tableName, String recordId) {
        this.recordId = recordId;
        this.tableName = tableName;
    }

    public String getRecordIdentifier() {
       return this.tableName + ":" + this.recordId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Record record = (Record) o;
        return Objects.equals(recordId, record.recordId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(recordId);
    }
}
