package de.tilokowalski.db;

import lombok.Getter;
import lombok.Setter;

import java.util.Objects;

/**
 * A record is a node in the surreal graph database.
 * It is identified by a table name and a record id.
 */
public abstract class Record implements RecordTableName {

    /**
     * The record id is optional.
     * If it is not set, the record id will be generated by surreal
     */
    @Getter
    @Setter
    private String id;



    /**
     * Creates a new record.
     *
     * @param recordId The record id.
     */
    protected Record(String recordId) {
        this.id = recordId;
    }

}
