package de.tilokowalski.db;

import lombok.Getter;

import java.util.Objects;

/**
 * A record is an entry in the surreal graph database.
 * It is identified by a table name and a record id.
 * Based on the <a href="https://docs.rs/surrealdb/1.0.0/surrealdb/sql/struct.Thing.html">rust library implementation of "Thing"</a>
 */
public abstract class Thing {

    /**
     * The record id is optional.
     * If it is not set, the record id will be generated by surreal
     * TODO: Create Id enum like rust lib does: <a href="https://docs.rs/surrealdb/1.0.0/surrealdb/sql/enum.Id.html">Id</a>
     */
    @Getter
    private transient String recordId;

    @Getter
    private transient String tableName;

    /**
     * Creates a new record.
     *
     * @param recordId The record id.
     */
    public Thing(String tableName, String recordId) {
        this.recordId = recordId;
        this.tableName = tableName;
    }

    @Override
    public String toString() {
       return this.tableName + ":" + this.recordId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Thing thing = (Thing) o;
        return Objects.equals(recordId, thing.recordId) && Objects.equals(tableName, thing.tableName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(tableName, recordId);
    }
}
